sudo: required
dist: trusty
language: node_js
git:
  depth: 3
branches:
  only:
  - master
cache:
  directories:
  - node_modules
node_js:
- '6.4'
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
install:
 - npm install
script: npm run ci
after_script: npm run compile:aot
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: ytplay
  region: us-west-2
  skip_cleanup: true
  local-dir: dist/client
  acl: public_read
  detect_encoding: true
  on:
    branch: master

## Setup notifications
notifications:
  email:
    on_success: change
    on_failure: change
